create table daily_record_cosmetic_set_items (
    daily_record_cosmetic_set_item_id bigint generated by default as identity,
    daily_record_cosmetic_set_id bigint not null,
    user_cosmetic_id bigint not null,
    sort_order integer not null,
    created_at timestamp(6) not null,
    primary key (daily_record_cosmetic_set_item_id),
    constraint uk_daily_record_set_items_cosmetic
        unique (daily_record_cosmetic_set_id, user_cosmetic_id),
    constraint uk_daily_record_set_items_sort
        unique (daily_record_cosmetic_set_id, sort_order),
    constraint fk_daily_record_set_items_set
        foreign key (daily_record_cosmetic_set_id)
            references daily_record_cosmetic_sets (daily_record_cosmetic_set_id),
    constraint fk_daily_record_set_items_user_cosmetic
        foreign key (user_cosmetic_id)
            references user_cosmetics (user_cosmetic_id)
);

insert into daily_record_cosmetic_set_items (
    daily_record_cosmetic_set_id,
    user_cosmetic_id,
    sort_order,
    created_at
)
select
    record_set.daily_record_cosmetic_set_id,
    set_item.user_cosmetic_id,
    row_number() over (
        partition by record_set.daily_record_cosmetic_set_id
        order by set_item.item_order, set_item.cosmetic_set_item_id
    ),
    record_set.created_at
from daily_record_cosmetic_sets record_set
join cosmetic_set_items set_item
    on set_item.cosmetic_set_id = record_set.source_cosmetic_set_id
join daily_record_cosmetics record_cosmetic
    on record_cosmetic.daily_record_id = record_set.daily_record_id
    and record_cosmetic.user_cosmetic_id = set_item.user_cosmetic_id
    and record_cosmetic.usage_period = record_set.usage_period;

alter table daily_reports
    add column generation_version bigint default 0 not null;
