create table record_reminder_deliveries (
    record_reminder_delivery_id bigint generated by default as identity,
    user_id bigint not null,
    reminder_date date not null,
    notification_status varchar(20) default 'pending' not null,
    notification_started_at timestamp(6),
    notification_attempt_id varchar(36),
    notification_sent_at timestamp(6),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (record_reminder_delivery_id),
    constraint uk_record_reminder_deliveries_user_date
        unique (user_id, reminder_date),
    constraint fk_record_reminder_deliveries_user
        foreign key (user_id) references users (user_id)
);

create index idx_record_reminder_delivery_schedule
    on record_reminder_deliveries (
        reminder_date,
        notification_status,
        notification_started_at
    );

create index idx_record_reminder_setting_schedule
    on user_notification_settings (
        record_reminder_enabled,
        record_reminder_time,
        user_id
    );
