
    create table anonymous_sessions (
        anonymous_session_id bigint generated by default as identity,
        created_at timestamp(6) not null,
        expires_at timestamp(6) not null,
        last_accessed_at timestamp(6),
        user_id bigint not null,
        token_hash varchar(64) not null,
        primary key (anonymous_session_id),
        constraint uk_anonymous_sessions_token_hash unique (token_hash)
    );

    create table cosmetic_ingredients (
        ingredient_order integer not null,
        is_main boolean not null,
        cosmetic_ingredient_id bigint generated by default as identity,
        cosmetic_product_id bigint not null,
        ingredient_id bigint,
        ingredient_name varchar(100) not null,
        primary key (cosmetic_ingredient_id),
        constraint uk_cosmetic_ingredients_product_order unique (cosmetic_product_id, ingredient_order)
    );

    create table cosmetic_products (
        cosmetic_product_id bigint generated by default as identity,
        created_at timestamp(6) not null,
        created_by_user_id bigint,
        updated_at timestamp(6) not null,
        source_type varchar(20) not null,
        product_type varchar(50) not null,
        brand_name varchar(100),
        product_name varchar(255) not null,
        source_key varchar(255),
        image_url clob,
        primary key (cosmetic_product_id)
    );

    create table cosmetic_set_items (
        item_order integer not null,
        cosmetic_set_id bigint not null,
        cosmetic_set_item_id bigint generated by default as identity,
        created_at timestamp(6) not null,
        user_cosmetic_id bigint not null,
        primary key (cosmetic_set_item_id),
        constraint uk_cosmetic_set_items_set_cosmetic unique (cosmetic_set_id, user_cosmetic_id),
        constraint uk_cosmetic_set_items_set_order unique (cosmetic_set_id, item_order)
    );

    create table cosmetic_sets (
        cosmetic_set_id bigint generated by default as identity,
        created_at timestamp(6) not null,
        updated_at timestamp(6) not null,
        user_id bigint not null,
        name varchar(100) not null,
        usage_time enum ('BOTH','MORNING','NIGHT') not null,
        primary key (cosmetic_set_id)
    );

    create table daily_health_summaries (
        average_heart_rate integer,
        body_water_mass_kg numeric(5,2),
        exercise_minutes integer,
        exercise_performed boolean,
        hrv_rmssd numeric(7,2),
        hydration_intake_ml integer,
        max_heart_rate integer,
        resting_heart_rate integer,
        skin_temperature_celsius numeric(4,2),
        sleep_minutes integer,
        steps integer,
        summary_date date not null,
        calculated_at timestamp(6) not null,
        daily_health_summary_id bigint generated by default as identity,
        user_id bigint not null,
        stress_level varchar(20),
        menstruation_status varchar(30),
        primary key (daily_health_summary_id),
        constraint uk_daily_health_summaries_user_date unique (user_id, summary_date)
    );

    create table daily_record_cosmetics (
        created_at timestamp(6) not null,
        daily_record_cosmetic_id bigint generated by default as identity,
        daily_record_id bigint not null,
        user_cosmetic_id bigint not null,
        usage_period varchar(10) not null,
        product_type_snapshot varchar(50) not null,
        brand_name_snapshot varchar(100),
        custom_name_snapshot varchar(100),
        ingredients_snapshot json,
        product_name_snapshot varchar(255) not null,
        primary key (daily_record_cosmetic_id)
    );

    create table daily_record_images (
        sort_order integer not null,
        created_at timestamp(6) not null,
        daily_record_id bigint not null,
        daily_record_image_id bigint generated by default as identity,
        file_size bigint not null,
        mime_type varchar(50) not null,
        object_key varchar(500) not null,
        primary key (daily_record_image_id),
        constraint uk_daily_record_images_object_key unique (object_key),
        constraint uk_daily_record_images_record_sort unique (daily_record_id, sort_order)
    );

    create table daily_records (
        record_date date not null,
        created_at timestamp(6) not null,
        daily_record_id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        user_id bigint not null,
        skin_status varchar(20) not null,
        food_memo varchar(300),
        memo varchar(300),
        primary key (daily_record_id),
        constraint uk_daily_records_user_date unique (user_id, record_date)
    );

    create table daily_reports (
        created_at timestamp(6) not null,
        daily_health_summary_id bigint unique,
        daily_record_id bigint not null unique,
        daily_report_id bigint generated by default as identity,
        generated_at timestamp(6),
        regenerated_at timestamp(6),
        updated_at timestamp(6) not null,
        report_status varchar(20) not null,
        note varchar(300),
        ai_analysis clob,
        ai_summary clob,
        personalized_solution clob,
        primary key (daily_report_id)
    );

    create table health_connections (
        connected_at timestamp(6) not null,
        health_connection_id bigint generated by default as identity,
        last_synced_at timestamp(6),
        revoked_at timestamp(6),
        user_id bigint not null,
        device_token_hash varchar(64) not null,
        device_id varchar(255) not null,
        primary key (health_connection_id),
        constraint uk_health_connections_user_device unique (user_id, device_id),
        constraint uk_health_connections_device_token_hash unique (device_token_hash)
    );

    create table health_raw_records (
        created_at timestamp(6) not null,
        end_time timestamp(6),
        health_connection_id bigint not null,
        health_raw_record_id bigint generated by default as identity,
        start_time timestamp(6) not null,
        updated_at timestamp(6) not null,
        record_type varchar(50) not null,
        hc_record_id varchar(255) not null,
        payload json not null,
        primary key (health_raw_record_id),
        constraint uk_health_raw_records_connection_record unique (health_connection_id, hc_record_id)
    );

    create table ingredients (
        created_at timestamp(6) not null,
        ingredient_id bigint generated by default as identity,
        name varchar(100) not null,
        primary key (ingredient_id),
        constraint uk_ingredients_name unique (name)
    );

    create table push_tokens (
        created_at timestamp(6) not null,
        push_token_id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        user_id bigint not null,
        token varchar(512) not null,
        device_id varchar(255) not null,
        primary key (push_token_id),
        constraint uk_push_tokens_user_device unique (user_id, device_id),
        constraint uk_push_tokens_token unique (token)
    );

    create table skin_care_tips (
        is_active boolean not null,
        created_at timestamp(6) not null,
        skin_care_tip_id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        content varchar(500) not null,
        primary key (skin_care_tip_id)
    );

    create table user_consents (
        agreed boolean not null,
        agreed_at timestamp(6) not null,
        consent_id bigint generated by default as identity,
        created_at timestamp(6) not null,
        user_id bigint not null,
        version varchar(20) not null,
        consent_type varchar(50) not null,
        primary key (consent_id),
        constraint uk_user_consents_user_type_version unique (user_id, consent_type, version)
    );

    create table user_cosmetics (
        cosmetic_product_id bigint not null,
        created_at timestamp(6) not null,
        deleted_at timestamp(6),
        updated_at timestamp(6) not null,
        user_cosmetic_id bigint generated by default as identity,
        user_id bigint not null,
        custom_name varchar(100),
        primary key (user_cosmetic_id)
    );

    create table user_daily_skin_care_tips (
        tip_date date not null,
        created_at timestamp(6) not null,
        skin_care_tip_id bigint not null,
        user_daily_tip_id bigint generated by default as identity,
        user_id bigint not null,
        primary key (user_daily_tip_id),
        constraint uk_user_daily_skin_care_tips_user_date unique (user_id, tip_date)
    );

    create table user_notification_settings (
        daily_report_enabled boolean not null,
        record_reminder_enabled boolean not null,
        record_reminder_time time(0),
        weekly_report_enabled boolean not null,
        weekly_report_time time(0),
        created_at timestamp(6) not null,
        notification_setting_id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        user_id bigint not null unique,
        primary key (notification_setting_id)
    );

    create table users (
        created_at timestamp(6) not null,
        profile_completed_at timestamp(6),
        updated_at timestamp(6) not null,
        user_id bigint generated by default as identity,
        age_group varchar(10),
        gender varchar(10),
        nickname varchar(10),
        skin_type varchar(30),
        primary key (user_id)
    );

    create table weekly_report_analyses (
        sort_order integer not null,
        weekly_report_analysis_id bigint generated by default as identity,
        weekly_report_id bigint not null,
        content clob not null,
        primary key (weekly_report_analysis_id),
        constraint uk_weekly_report_analyses_report_sort unique (weekly_report_id, sort_order)
    );

    create table weekly_reports (
        week_end_date date not null,
        week_start_date date not null,
        created_at timestamp(6) not null,
        generated_at timestamp(6) not null,
        regenerated_at timestamp(6),
        updated_at timestamp(6) not null,
        user_id bigint not null,
        weekly_report_id bigint generated by default as identity,
        note varchar(300),
        personalized_solution clob not null,
        weekly_summary clob not null,
        primary key (weekly_report_id),
        constraint uk_weekly_reports_user_start unique (user_id, week_start_date)
    );

    create index idx_cosmetic_products_product_name 
       on cosmetic_products (product_name);

    create index idx_daily_health_summaries_summary_date 
       on daily_health_summaries (summary_date);

    create index idx_health_raw_records_record_type 
       on health_raw_records (record_type);

    create index idx_health_raw_records_start_time 
       on health_raw_records (start_time);

    create index idx_user_cosmetics_user_deleted 
       on user_cosmetics (user_id, deleted_at);

    alter table if exists anonymous_sessions 
       add constraint FKq8291s5589tkwyt3d2o63h0xb 
       foreign key (user_id) 
       references users;

    alter table if exists cosmetic_ingredients 
       add constraint FK83isb85ytr6cxcxbk6yk5snnd 
       foreign key (cosmetic_product_id) 
       references cosmetic_products;

    alter table if exists cosmetic_ingredients 
       add constraint FKl0weuql6iieuvwuastnnkdl28 
       foreign key (ingredient_id) 
       references ingredients;

    alter table if exists cosmetic_products 
       add constraint FKa3cdtrle8x710bmcmg53sy8op 
       foreign key (created_by_user_id) 
       references users;

    alter table if exists cosmetic_set_items 
       add constraint FKlmmmgkhy28x7ryo157fga76n2 
       foreign key (cosmetic_set_id) 
       references cosmetic_sets;

    alter table if exists cosmetic_set_items 
       add constraint FKp28wmrqyxh2lnhbfhxhchsogk 
       foreign key (user_cosmetic_id) 
       references user_cosmetics;

    alter table if exists cosmetic_sets 
       add constraint FKblxmy4oynk4apntlsd6rkxixo 
       foreign key (user_id) 
       references users;

    alter table if exists daily_health_summaries 
       add constraint FKsowb09yd4tlvvdai5yoi372ce 
       foreign key (user_id) 
       references users;

    alter table if exists daily_record_cosmetics 
       add constraint FKpuyp702bxraoftkg9dna076cq 
       foreign key (daily_record_id) 
       references daily_records;

    alter table if exists daily_record_cosmetics 
       add constraint FKwhvihgrfdi40ayd0ll10kp6n 
       foreign key (user_cosmetic_id) 
       references user_cosmetics;

    alter table if exists daily_record_images 
       add constraint FK811q4p0pf3uj6e03u55qwpg3q 
       foreign key (daily_record_id) 
       references daily_records;

    alter table if exists daily_records 
       add constraint FK8lraprtn3xr7kik4ir2w3k31a 
       foreign key (user_id) 
       references users;

    alter table if exists daily_reports 
       add constraint FKnjqovgog8skom2a11itra6w5o 
       foreign key (daily_health_summary_id) 
       references daily_health_summaries;

    alter table if exists daily_reports 
       add constraint FK1fpdp6lmjfnkjhebysmd2xeou 
       foreign key (daily_record_id) 
       references daily_records;

    alter table if exists health_connections 
       add constraint FKi7b42ifkbs4vkitoao30khe49 
       foreign key (user_id) 
       references users;

    alter table if exists health_raw_records 
       add constraint FKkhcgwe3o5n23nyms8lhh3m98f 
       foreign key (health_connection_id) 
       references health_connections;

    alter table if exists push_tokens 
       add constraint FKgisqbur2nbpemhidpyqv501nd 
       foreign key (user_id) 
       references users;

    alter table if exists user_consents 
       add constraint FK2jrdhofjcd44quyuq5x9wlb8b 
       foreign key (user_id) 
       references users;

    alter table if exists user_cosmetics 
       add constraint FKjle9vq37aiweollrgltomouv9 
       foreign key (cosmetic_product_id) 
       references cosmetic_products;

    alter table if exists user_cosmetics 
       add constraint FKl9jghobetthqkui3h1tjtrnx8 
       foreign key (user_id) 
       references users;

    alter table if exists user_daily_skin_care_tips 
       add constraint FK4runk1ejenu3cq4yvn52ni1c9 
       foreign key (skin_care_tip_id) 
       references skin_care_tips;

    alter table if exists user_daily_skin_care_tips 
       add constraint FKs3r7xwei852685w4b9a7y3ekp 
       foreign key (user_id) 
       references users;

    alter table if exists user_notification_settings 
       add constraint FKs9tjvxu8ko31ivjlq9l9duh9y 
       foreign key (user_id) 
       references users;

    alter table if exists weekly_report_analyses 
       add constraint FK551dneaoiocbmtcyj64o5c9d8 
       foreign key (weekly_report_id) 
       references weekly_reports;

    alter table if exists weekly_reports 
       add constraint FKqmbqcc7qb4mfr8wbc2xecqwin 
       foreign key (user_id) 
       references users;
