alter table daily_record_cosmetics
    add column sort_order integer default 0 not null;

update daily_record_cosmetics target
set sort_order = (
    select count(*)
    from daily_record_cosmetics candidate
    where candidate.daily_record_id = target.daily_record_id
      and candidate.usage_period = target.usage_period
      and candidate.daily_record_cosmetic_id <= target.daily_record_cosmetic_id
);

alter table daily_record_cosmetics
    add constraint uk_daily_record_cosmetics_user_period
        unique (daily_record_id, user_cosmetic_id, usage_period);

alter table daily_record_cosmetics
    add constraint uk_daily_record_cosmetics_sort
        unique (daily_record_id, usage_period, sort_order);

create table daily_record_cosmetic_sets (
    sort_order integer not null,
    created_at timestamp(6) not null,
    daily_record_cosmetic_set_id bigint generated by default as identity,
    daily_record_id bigint not null,
    source_cosmetic_set_id bigint not null,
    set_name_snapshot varchar(100) not null,
    set_usage_time_snapshot varchar(20) not null,
    usage_period varchar(10) not null,
    primary key (daily_record_cosmetic_set_id),
    constraint uk_daily_record_sets_source_period
        unique (daily_record_id, source_cosmetic_set_id, usage_period),
    constraint uk_daily_record_sets_sort
        unique (daily_record_id, usage_period, sort_order),
    constraint fk_daily_record_cosmetic_sets_record
        foreign key (daily_record_id) references daily_records
);
